version: '3.6'

services: 
  jupyterlab:
    build: .
    ports: 
      - 8888:8888
    volumes: 
      - ./tf-knugs:/tf-knugs
    deploy:
      resources: 
        reservations:
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]

